// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shelter.Models;

namespace Shelter.Migrations
{
    [DbContext(typeof(ShelterContext))]
    [Migration("20220122003102_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Shelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 3,
                            Name = "Rufus",
                            Sex = "Male",
                            Species = "French Bulldog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 6,
                            Name = "Felix",
                            Sex = "Male",
                            Species = "Siamese Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 5,
                            Name = "Annabelle",
                            Sex = "Female",
                            Species = "English Springer Spaniel"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 2,
                            Name = "Tater Tot",
                            Sex = "Male",
                            Species = "Pomeranian Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 1,
                            Name = "Princess",
                            Sex = "Male",
                            Species = "Persian Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
